name: sipantau
description: Aplikasi Monitoring Kendaraan SIPANTAU
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Font agar mirip desain Figma
  google_fonts: ^6.1.0
  # Ikon tambahan
  cupertino_icons: ^1.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: 6.2.1
  shared_preferences: ^2.5.4
  firebase_storage: ^13.0.4
  image_picker: ^1.2.1
  cloud_firestore: ^6.1.0
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Mendaftarkan folder assets
  assets:
    - assets/